### ISSUE TITLE
make sure scan, build dep tree, and score tasks terminate 

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#100]
refs: #75 

These have run over the weekend without being terminated.

per chat https://app.slack.com/client/T027LFU12/GU785MMRV :

> make sure those terminate (I believe it's due to all the package graphs not being trees) and probably adding unit tests to show that are the first priority

> our celery config should kill long running tasks but I think either the recursion in dep tree scoring or the sqla transport prevent that from happening

**Comment by g-k** [comment]
@mozmark do you have any context? / does the dep tree builder assume the package graphs are trees?

**Comment by mozmark** [comment]
It does - I'll add cycle detection.

**Comment by g-k** [comment]
I started looking into this, but have mostly been wrapping my head around the code.

**Comment by g-k** [comment]
tentatively fixed in #120

**Comment by g-k** [comment]
still busted for https://localhost:8000/?manager=npm&package=fxa-jwtool&version=0.7.2
