### ISSUE TITLE
Option to show vulnerabilities for package/dependencies

### ISSUE THREAD

**Issue by psiinon** [mozilla-services/dependency-observatory#107]
We're exposing the number and type of known vulnerabilities for packages and dependencies, but as a dev the first thing I'd want to know are - what are they??
We have that info so would just need a suitable API and UI.

**Comment by g-k** [comment]
Do we just need the UI to hit the vulns endpoint and display that data?

**Comment by psiinon** [comment]
Thats the plan :)
