### ISSUE TITLE
Add CORS header for non-local API testing

### ISSUE THREAD

**Issue by mozmark** [mozilla-services/dependency-observatory#12]
@psiinon what value would you like? I can get to this first thing.

**Comment by psiinon** [comment]
Any reason we wouldnt want to go with `Access-Control-Allow-Origin: *` ?
That would mean anyone could include the API calls on any site, but we want to make this as consumable as possible, right?

**Comment by mozmark** [comment]
Certainly that will be fine for now. I can't forsee any issues with this but we can ask the wider group.
