### ISSUE TITLE
handle cycles in graphs

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#141]
Initially we skipped this since we weren't sure how often it occurs in practice, but it came up for:

https://depobs.dev.mozaws.net/?manager=npm&package=fxa-jwtool&version=0.7.2
w/ graph https://depobs.dev.mozaws.net/graphs/3043

![image](https://user-images.githubusercontent.com/226605/78383615-adda3080-75a6-11ea-9428-588bfa9c7625.png)

which has cycles in:

`es-abstract@1.17.5 <> string.prototype.trimright@2.1.2 [<> string.prototype.trimend@1.0.0]`
`es-abstract@1.17.5 <> string.prototype.trimleft@2.1.2 [<> string.prototype.trimstart@1.0.0]`

and possibly elsewhere.

**Comment by g-k** [comment]
refs: https://github.com/mozilla-services/dependency-observatory/issues/130#issuecomment-608017713

**Comment by g-k** [comment]
We probably want to: 

- [ ] detect cycles and highlight them in the graph view 
- [ ] collect data on # of cycles and cycle size

**Comment by g-k** [comment]
cc @mozmark who's been thinking about this

**Comment by mozmark** [comment]
Ok, so my thoughts are as follows:
-  We cannot find cycles without either a) some additional state, or b) expensive re-traversals of parts of the graph. My hunch is that 'a' is the better option
- We only have state on individual paths of the graph at a given time during scoring and graph build (since we enqueue based on individual usages)
- Each package has many paths (since a given package may use and be used by a number of others)
- Therefore, for a given usage, that path should be stored with the package and propagated to dependencies
- On receipt of a path, the graph builder for a package can check for its own identifier in the provided path list. If it finds it, you have all of the information you need for capturing the cycle information. If not, repeat for dependencies


I've been sketching this out in code today but kinda struggling.

**Comment by g-k** [comment]
Not sure I completely follow, but that sounds good to me. Some of my questions and thoughts:

* Are we talking about the graphs for a single scan (i.e. a single `package_graphs` row)? And is a package usage one A depends on B edge? 

* The largest `package_graphs` row we have in -dev has ~3.3k edges. Most are substantially smaller. I'm not sure that representative of the larger ecosystem. The analysis happens offline with scan time dominating, so additional state sounds good, but re-traversal wouldn't be the end of the world.

I think it'd be useful to define what scores we expect for a few simple graphs (possibly with properties of how they combine) then try to come up with a scoring and traversal algorithm.

Some examples with cycles I can add as failing test cases for now: 

a self loop: A -> A -> A (we're looking at unique dependencies of A so I don't think the score would change)
a single direct dep. loop: A -> B -> A (A and B pick up a direct dependency, might be able to but the cycle and score each node?)
a single indirect dep. loop: A -> B -> C -> A (each picks up 1 direct and indirect dependency)
multiple loops sharing one node: A -> B -> A and A -> C -> A (we define sort of adding over scored loops?)
nested loops sharing two nodes: A -> B -> C -> A , A -> B -> A, A -> C -> A

In terms of traversal, I was roughly thinking:

1.  run a cycle detection algorithm: https://networkx.github.io/documentation/stable/reference/algorithms/cycles.html
1. score the cycle  
1. try to cut or collapse the cycle to a constant that gets added to each node in it
1. proceed with the tree based scoring

There might be something interesting in the adjacency matrix and probably relevant research somewhere.

**Comment by g-k** [comment]
also `eslint@6.8.0`

**Comment by g-k** [comment]
> For each node in the list, the script will find every upstream node in the callgraph, and increment their badness by one, thus indicating that they use unsafety at some point in their execution. At the end of this process, all the nodes with nonzero badness are printed out, sorted in descending order by badness.

https://github.com/trailofbits/siderophile#how-it-works

**Comment by g-k** [comment]
Current WIP:

* find the condensate of the graph to get a DAG with cycles collapsed / condensed
* iterate through the condensate DAG as usual ("outside" in) scoring the nodes in overlapping strongly connected components (i.e. our `scoring-in-progress` nodes / gray zone). This will also requires changing `score_package_and_children` to fetch and score a cycle or overlapping cycles and remapping the `descendents`.
