### ISSUE TITLE
link to npms.io score in report

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#148]
e.g. the API endpoint with the analysis https://api.npms.io/v2/package/hapi and search result https://npms.io/search?q=hapi

**Comment by psiinon** [comment]
Are either of those really good links?
The first you really have to delve into the structure, and the second depends on search results and only gives the latest score.

**Comment by g-k** [comment]
> Are either of those really good links?

Not really :|

>  I havnt found any better ones btw ;)

Yeah, I guess we could check with the npms.io team to make sure we there isn't a more detailed report page for a specific package and version we're missing.

**Comment by psiinon** [comment]
How do we get from http://localhost:8000/?manager=npm&package=%40hapi%2Fbounce&version=2.0.0 to https://api.npms.io/v2/package/hapi ?
The package name we have is @hapi/bounce - but we need to use hapi.
However there is a real but depreciated hapi package: https://www.npmjs.com/package/hapi and thats actually linked to from the above API call :(

**Comment by psiinon** [comment]
Ah ha, https://api.npms.io/v2/package/%40hapi%2Fbounce works :)
