### ISSUE TITLE
improve accuracy of npms.io scores for older packages

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#260]
npms.io scores are a base component of npm package scores. 

However, we use current npms.io scores for older versions of a package, which doesn't necessarily reflect the state of the package at the time the version was cut.

Considerations:

Can we get old npms.io scores? 

No, after reaching out to the maintainers they only keep the latest version and do not dump historical scores somewhere (makes sense because it's a lot of data to store and people are probably most interested in the latest version of a package).

Can we reconstruct npms.io scores for older versions?

The [npms.io infrastructure](https://github.com/npms-io/npms-analyzer/blob/master/docs/architecture.md) includes couchdb, a queue, workers, and elasticsearch. It would probably require a non-trivial amount of money and time to run and be limited to one language and registry. Also, we cannot guarantee we'll be able to reconstruct its inputs (e.g. GH stars) for a given point in time.

**Comment by g-k** [comment]
A few options I've discussed with @psiinon:

* reduce the impact of npms.io scores on older package versions (e.g. in terms of time since publication, LOC changed since then or both). Could be linear or [exponential / Holt-Winters](https://en.wikipedia.org/wiki/Exponential_smoothing) depending on how quickly we expect the accuracy of the score to drop off.

* increase the impact of vulnerabilities, since we'd expect more to be reported over time

* remove the npms.io score factor from package version scores, but compute a score for each package name e.g. the score for a given package is a weighted sum of scores for its versions

**Comment by psiinon** [comment]
The npms.io score is really non trivial to calculate, but I think it provides a lot of value. So I dont really want to drop it for all package/versions and dropping it for just some could really skew the results.
So my suggestion is that we still use the npms.io score for older packages but that we flag is somehow - time based sounds like the easiest option to start with. We can then use that data to adjust the score.

**Comment by g-k** [comment]
Discussed with Simon and we can use the package version npms.io scores (from `.collected.metadata.version` in the API response which we store in the `npmsio_scores` table in the `package_version` column). We store multiple npmsio scores with different analyzed_at fields values so we can use the closest matching one.

Probably requires the following changes:

* in `database.models` `PackageGraph.get_npmsio_scores_by_package_version_id` falls back to looking for a score just by package name and returning the scored `package_version` from the `npmsio_scores` table i.e. instead of `Dict[PackageVersionID, Optional[float]]` it returns the whole NPMSIOScore model or something including the scored `package_version`

* add the scored package version field to `NPMSIOScoreComponent.package_report_fields`, update the staticmethods on that class to take the new input type, add/update the unit tests: https://github.com/mozilla-services/dependency-observatory/blob/ac71118342a188eb2b11ae2b3a4eb9e824ca1ab7/tests/worker/test_scoring.py#L107-L130

* add the scored package version field or flag indicated we're using a different package version to PackageReport

* update the API response

* update the UI to show a warning

**Comment by psiinon** [comment]
Current plan is to add the lowest available npmsio to the reports table along with the npmsio_score_version - we can then use that to detect its not the 'correct' one and adjust accordingly.
