### ISSUE TITLE
move scoring into a db view

### ISSUE THREAD

**Issue by psiinon** [mozilla-services/dependency-observatory#282]
This should allow us to try out alternative scoring methodologies without having to rescore everything.

- [x] Create view manually
- [x] Add defn to code #283
- [x] Create view model
- [x] Use view in UI

**Comment by g-k** [comment]
Played with the db schema on this branch: https://github.com/mozilla-services/dependency-observatory/compare/debug-views?expand=1 

It works in CI with a basic scan https://app.circleci.com/pipelines/github/mozilla-services/dependency-observatory?branch=debug-views

It has scans passing and returns `score` and `score_code` columns, however for my local scan I still get a `null` score back not sure why that's the case, but maybe we can define `score` and `score_code` with one view.

The change I was missing was to make sure the dependencies relationships have different `backref` values. We could also do this with a declared attr: https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/mixins.html#using-advanced-relationship-arguments-e-g-primaryjoin-etc

Also, when I had an invalid schema, celery was exiting with 1 and zero context.
