### ISSUE TITLE
handle multiple k8s clusters

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#368]
per @erkolson in stage or prod we'll use separate nodes on a different cluster for the untrusted package jobs vs the local web server and jobs, so:

1. ideally update the local k8s config to match clusters in stage/prod (or configure them to alias to the same one or use one and have the same config picked for both job types)
1. update k8s job code to pick a client for the right cluster https://github.com/kubernetes-client/python/blob/master/examples/multiple_clusters.py  
1. probably update the service account perms and cluster role bindings such that:
  * jobs started in the web server cluster should have access to start jobs in the untrusted cluster
  * jobs in the untrusted cluster should not have permissions to start jobs elsewhere (and generally restricted perms)

^ assumes https://github.com/mozilla-services/dependency-observatory/pull/359 lands in some form

**Comment by erkolson** [comment]
The worker pods that spin up jobs will need to have access to the google cloud sdk (gcloud cli) to auth to the second cluster's api server.  The python client actually [shells out to gcloud](https://github.com/kubernetes-client/python-base/blob/master/config/kube_config.py#L158) to acquire and refresh access tokens.

I thought there might be another way to auth with the other kuberenetes api server using only a gcp token but I can't find it in the client (or [python base](https://github.com/kubernetes-client/python-base) which is used by the client)

**Comment by erkolson** [comment]
@g-k I have a branch that installs gcloud, can you give me write access to push it to this repository?

**Comment by g-k** [comment]
@erkolson added!

**Comment by g-k** [comment]
> The python client actually shells out to gcloud to acquire and refresh access tokens.

wtf
