### ISSUE TITLE
visualize score distributions

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#425]
We'd like to see the impact of changes like #421 on the scores and score codes / letter grades of all scanned packages in the DB.

A few visualization options:

* copy https://observatory.mozilla.org/statistics/ https://github.com/mozilla/http-observatory/search?q=%2Fstatistics&unscoped_q=%2Fstatistics
* something from https://seaborn.pydata.org/tutorial/distributions.html
* something else

I think we want histograms of:

- [x] score # on from 0 to 100 inclusive binned in intervals of 10
- [x] score code / letter grade

Eventually we'd also like it to look at subsets of all scanned packages (e.g. Top N, from Mozilla repos, from a repo lockfile) and distributions of other score components (# of dep, # of maintainers, etc.).

**Comment by g-k** [comment]
Fixed in #446

**Comment by alex-bellon** [comment]
Quick fix in #452
