### ISSUE TITLE
make sure scoring finishes

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#458]
Currently the worker waits for both:

* all running k8s jobs to finish
* then receiving a pubsub message with job complete from all jobs

before scoring the packages and updating the scan state to succeeded or failed.

We should make sure the worker process finishes scoring jobs when it dies or a deploy occurs.

@erkolson how does a deploy impact running deployments? Will k8s send a signal to the worker process on restart?

**Comment by erkolson** [comment]
Kubernetes shuts down pods by first sending SIGTERM, waiting 30 seconds, then sending SIGKILL.  If the worker should trap SIGTERM and shut itself down gracefully.  That is of a pod being deleted.  There are times when containers can get shutdown faster.  For example, if there are limited resources (OOM killer, etc)

**Comment by g-k** [comment]
OK thanks, it sounds like the worker should:

- [ ] attempt to finish scoring incomplete jobs on worker start
- [ ] run with `uwsgi` so we can tune concurrency params and not implement our own daemon
- [ ] use the uwsgi `--die-on-term` https://uwsgi-docs.readthedocs.io/en/latest/Management.html#signals-for-controlling-uwsgi and make sure tasks save results within 30s or can be rerun
