### ISSUE TITLE
investigate replacing scoring views with mapped properties

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#465]
- [x] read or skim https://docs.sqlalchemy.org/en/13/orm/mapped_sql_expr.html
- [ ] decide whether to replace scoring view columns with python `hybrid_property` or sql `column_property` or both

**Comment by g-k** [comment]
motivated by #457 and other scoring changes

**Comment by g-k** [comment]
cc @alex-bellon

**Comment by alex-bellon** [comment]
- Tried using `@hybrid_property` but you're not able to directly access the value of attributes, so you can't do comparisons with them
- Started trying to get `column_property` working, but was having trouble translating the SQL queries to valid SQLAlchemy syntax
