### ISSUE TITLE
add another database view with old scoring scheme

### ISSUE THREAD

**Issue by alex-bellon** [mozilla-services/dependency-observatory#477]
Add another view and class to allow the statistics page to display graphs for the old scoring scheme. This will make it easier to visually compare how different scoring schemes affects the distribution of letter/number scores.

Later on, this can be switched to something a bit less hacky than a new view and class per scoring version. Links from @g-k :
- https://docs.sqlalchemy.org/en/13/orm/mapping_api.html#sqlalchemy.orm.Mapper
- https://docs.sqlalchemy.org/en/13/core/inspection.html#sqlalchemy.inspect

**Comment by g-k** [comment]
:+1: in general problem it'd be good to have many ways to score dependencies depending on the user's security posture (e.g. tls config has different configs for different profiles)

**Comment by alex-bellon** [comment]
Added in #480
