### ISSUE TITLE
check DB and queue in heartbeat handler

### ISSUE THREAD

**Issue by g-k** [mozilla-services/dependency-observatory#73]
per https://github.com/mozilla-services/Dockerflow/#containerized-app-requirements for #8 

> Respond to /__heartbeat__ with a HTTP 200 or 5xx on error. This should check backing services like a database for connectivity and may respond with the status of backing services and application components as a JSON payload.

**Comment by jvehent** [comment]
fixed in #193

**Comment by g-k** [comment]
I guess it's ok if the queue goes down and we can monitor that separately.

**Comment by jvehent** [comment]
Since the queue is in the DB, I'd think monitoring the DB would be enough, no?
